#pragma once

enum GameState
{
	GAME_STATE_LOBBY,
	GAME_STATE_LOADING_TO_GAME,
	GAME_STATE_IN_GAME,
	GAME_STATE_PAUSED_GAME,
	GAME_STATE_CHECK_EXIT_TO_LOBBY,
	GAME_STATE_LOADING_TO_LOBBY,

	GAME_STATE_OPTION,
	GAME_STATE_CHECK_EXIT_TO_WINDOW,
};